#!/bin/bash
#
# Copyright 2016 MivoCloud S.R.L.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Turn off debugging
sed -i 's/DEBUG/WARNING/g' /etc/cloud/cloud.cfg.d/05_logging.cfg

# Allow password authentication
echo "ssh_pwauth: true" > /etc/cloud/cloud.cfg.d/99_custom.cfg

# Don't change the apt sources
echo "apt_preserve_sources_list: true" >> /etc/cloud/cloud.cfg.d/99_custom.cfg

# Don't update the hostname on boot
# We don't use the 'preserve_hostname' variable because we want the hostname
# to be set on first boot
sed -i 's/ - update_hostname/# - update_hostname/g' /etc/cloud/cloud.cfg

# Don't lock the password for the dafault user
sed -i 's/lock_passwd: True/lock_passwd: false/g' /etc/cloud/cloud.cfg

# Allow sudo wihtout password for the default user
sed -i 's/.*name: debian.*/&\n     sudo: ["ALL=(ALL) NOPASSWD:ALL"]/' /etc/cloud/cloud.cfg

# Set the shell to /bin/bash
sed -i 's/.*name: debian.*/&\n     shell: \/bin\/bash/' /etc/cloud/cloud.cfg
