#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo ""
echo "Running dracut -f"
echo ""

source /lib/diskimage-builder/img-functions

select_boot_kernel_initrd /

echo ${KERNEL} ${RAMDISK}

KERN=`echo ${KERNEL} | sed 's/vmlinuz-//g'`
RMDISK=/boot/${RAMDISK}

echo ${RMDISK} ${KERN}

dracut --force ${RMDISK} ${KERN}
